url:https://katalon-demo-cura.herokuapp.com/
LoginUrl:https://katalon-demo-cura.herokuapp.com/profile.php#login
MakeAppointment:https://katalon-demo-cura.herokuapp.com/#appointment
History:https://katalon-demo-cura.herokuapp.com/history.php#history
Profile:https://katalon-demo-cura.herokuapp.com/profile.php#profile
timeoutvalue:10
UserName:John Doe
Password:ThisIsNotAPassword
InvalidUser:harish
InvalidPassword:Harish084